# Data
data_name: 'yelp'
data_dir: './data/yelpchi/'
train_ratio: 0.4
test_ratio: 0.67
save_dir: './pytorch_models/'
gen_save_dir: './pytorch_models/gen/'

# Model
model: 'DiG-In-GNN'
multi_relation: 'GNN'

# Model architecture
emb_size: 128

thres: 0.5

rho: 0.5

seed: 123456789

#RL
ob_dim: 96
action_dim: 2
fc1_dim: 256
fc2_dim: 256
sample_rate1: 0.7
sample_rate2: 0.06
sample_rate3: 0.008
rl_tolerance1: 0.1
rl_tolerance2: 0.09
rl_tolerance3: 0.08
# hyper-parameters
optimizer: 'adam'
lr: 0.005
weight_decay: 0.001

gen_lr: 0.003
gen_weight_decay: 0.001

rl_lr1: 0.003
rl_lr2: 0.003
rl_lr3: 0.003
rl_weight_decay: 0.001

batch_size: 512
negsamp_ratio: 1
num_epochs: 162
valid_epochs: 1
alpha: 2

# Device
cuda: True
cuda_id: '0'
device: 'cuda:0'

# model_update
gnn_update_start: 72 # 81
gen_update_end: 71 # 80
rl_update_start: 72 # 81
rl_update_end: 190
label_update_end: 90
laod_gen: False
save_gen: False
gen_num: 80

# pick_step
b_pick: 0.9
f_pick: 0.45

pick: 4
